name: React App Workflow

baseDir: ./

steps:
  # Step 1: Install dependencies
  - run: 'npm install'

  # Step 2: Run tests
  - run: 'npm run test'

  # Step 3: Choose build type
  - choose:
      message: "Select build type:"
      options:
        - id: dev
          label: "Development Build"
        - id: prod
          label: "Production Build"
      as: buildType

  # Step 4: Build based on selection
  - when:
      var:
        buildType: dev
    run: 'echo "Building for development..." && npm run build'

  - when:
      var:
        buildType: prod
    run: 'echo "Building for production..." && npm run build'

  # Step 5: Verify build output
  - when:
      file: ./build
    run: 'echo "✓ Build directory created" && ls -la build/'

  # Step 6: Ask for deployment
  - prompt:
      message: "Enter deployment URL:"
      as: deployUrl
      default: "https://example.com"

  # Step 7: Deploy
  - run: 'echo "Deploying to {{deployUrl}}..."'

  # Step 8: Start dev server (optional)
  - choose:
      message: "Start development server?"
      options:
        - id: yes
          label: "Yes"
        - id: no
          label: "No"
      as: startServer

  - when:
      var:
        startServer: yes
    run: 'npm run start'

