name: Slack Settings

# 1) Load SLACK_TOKEN from env.example via cat + KV capture
# 2) Fetch workspace/auth info. Edit env.example with your token. Run from this directory. Requires Node.js 18+.

baseDir: ./

steps:
  - run: 'cat env.example'
    captures:
      - kv: SLACK_TOKEN
        as: SLACK_TOKEN
  - run: 'node get-settings.js "{{SLACK_TOKEN}}"'
  - run: 'echo "Done."'
