name: Slack Profile

# 1) Load SLACK_TOKEN from env.example via cat + KV capture
# 2) Optionally prompt for user ID, then fetch profile. Edit env.example with your token. Run from this directory. Requires Node.js 18+.

baseDir: ./

steps:
  - run: 'cat env.example'
    captures:
      - kv: SLACK_TOKEN
        as: SLACK_TOKEN
  - prompt:
      message: "Slack User ID (e.g. U01234, or leave empty for current user):"
      as: user_id
      default: ""
  - run: 'node get-profile.js "{{SLACK_TOKEN}}" "{{user_id}}"'
  - run: 'echo "Done."'
