/**
 * Rust Task Runner Module
 * Directly imports Rust NAPI module (auto-generated by @napi-rs/cli)
 */

import { getModulePaths, tryLoadModule } from './module-loader-utils';

// Type definitions
interface RustTaskRunnerModule {
  runTask(command: string): Promise<boolean>;
  runTaskSync(command: string): boolean;
}

// Type guard to check if module is RustTaskRunnerModule
function isRustTaskRunnerModule(module: unknown): module is RustTaskRunnerModule {
  return (
    typeof module === 'object' &&
    module !== null &&
    'runTask' in module &&
    typeof (module as RustTaskRunnerModule).runTask === 'function' &&
    'runTaskSync' in module &&
    typeof (module as RustTaskRunnerModule).runTaskSync === 'function'
  );
}

let rustModule: RustTaskRunnerModule | null = null;

/**
 * Load Rust module (dynamically require .node file in ESM)
 * Compatible with pkg packaging
 */
export async function loadRustModule(): Promise<RustTaskRunnerModule | null> {
  if (rustModule) return rustModule;

  try {
    const paths = getModulePaths('task-pipeliner-rs.node');
    const module = tryLoadModule(paths);
    if (module && isRustTaskRunnerModule(module)) {
      return (rustModule = module);
    }
  } catch {
    // Fallback
  }

  return null;
}
