/**
 * Rust Task Runner Module
 * Directly imports Rust NAPI module (auto-generated by @napi-rs/cli)
 */

// Type definitions
interface RustTaskRunnerModule {
  runTask(command: string): Promise<boolean>;
  runTaskSync(command: string): boolean;
}

let rustModule: RustTaskRunnerModule | null = null;

/**
 * Load Rust module (dynamically require .node file in ESM)
 */
export async function loadRustModule(): Promise<RustTaskRunnerModule | null> {
  if (rustModule) {
    return rustModule;
  }

  try {
    const path = await import('path');
    const { fileURLToPath } = await import('url');
    const { createRequire } = await import('module');

    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);
    const nodePath = path.resolve(__dirname, '../task-pipeliner-rs.node');

    // Use require to load .node file in ESM
    const require = createRequire(import.meta.url);
    const module = require(nodePath);

    if (module && 'runTask' in module) {
      rustModule = module as RustTaskRunnerModule;
      return rustModule;
    }
  } catch (_error) {
    // Return null if Rust module not found (use fallback)
    return null;
  }

  return null;
}
